apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: hsys
spec:
  replicas: 2
  selector:
    matchLabels: { app: gateway-service }
  template:
    metadata:
      labels: { app: gateway-service }
    spec:
      serviceAccountName: gateway-sa
      containers:
        - name: gateway
          image: andrewscl/gateway-service:latest
          ports: [ { containerPort: 8080 } ]
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8888
            - name: SPRING_PROFILES_ACTIVE
              value: default
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8080 }
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests: { cpu: "250m", memory: "512Mi" }
            limits:   { cpu: "1000m", memory: "1Gi" }
