apiVersion: v1
kind: Namespace
metadata:
  name: hsys
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-sa
  namespace: hsys
---
# RBAC mínimo para discovery en el namespace hsys
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: discovery-role
  namespace: hsys
rules:
  - apiGroups: [""]
    resources: ["services","endpoints","pods"]
    verbs: ["get","list","watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discovery-binding
  namespace: hsys
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: discovery-role
subjects:
  - kind: ServiceAccount
    name: gateway-sa
    namespace: hsys